# Generated by Django 5.2.7 on 2025-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='coping_action',
            field=models.CharField(max_length=5000),
        ),
    ]
